/************************************************************************

    reedsolomon.cpp

    ld-efm-encoder - EFM data encoder
    Copyright (C) 2025 Simon Inns

    This file is part of ld-decode-tools.

    ld-efm-encoder is free software: you can redistribute it and/or
    modify it under the terms of the GNU General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

************************************************************************/

#include <QDebug>

#include "reedsolomon.h"

#include "ezpwd/rs_base"
#include "ezpwd/rs"

ReedSolomon::ReedSolomon() {}

// Perform a C1 Reed-Solomon encoding operation on the input data
// This is a (32,28) Reed-Solomon code
QVector<uint8_t> ReedSolomon::c1_encode(QVector<uint8_t> input_data) {
    // Convert the QVector to a std::vector for the ezpwd library
    std::vector<uint8_t> tmp_data(input_data.begin(), input_data.end()-4);

    // Encode the data
    c1rs.encode(tmp_data);

    // Extract parity symbols
    std::vector<uint8_t> parity(tmp_data.begin() + 28, tmp_data.end());

    // Insert the parity bytes back into the original data (bytes 28-31)
    for (int i = 0; i < 4; ++i) {
        input_data[28 + i] = parity[i];
    }

    return input_data;
}

// Perform a C1 Reed-Solomon decoding operation on the input data
QVector<uint8_t> ReedSolomon::c1_decode(QVector<uint8_t> encoded_data) {
    // Convert the QVector to a std::vector for the ezpwd library
    std::vector<uint8_t> tmp_data(encoded_data.begin(), encoded_data.end());

    // Decode the data
    c1rs.decode(tmp_data);

    // Convert the std::vector back to a QVector
    encoded_data = QVector<uint8_t>(tmp_data.begin(), tmp_data.end());

    return encoded_data;
}

// Perform a C2 Reed-Solomon encoding operation on the input data
// This is a (28,24) Reed-Solomon code - it expects 24 bytes of input data
// and generates 4 parity bytes giving a total of 28 bytes of output data
//
// Note: This 100% doesn't work... There is some kind of specific
// FEC encoding that is done on the C2 data that I don't understand
// and I can't find any information on. I'm leaving this here for
// now as a placeholder.
//
// The issue is to do with the parity bytes that are generated by the
// encoder which cannot be simply moved from the end to the middle of
// the output data as decoding fails.
//
// I've tried to change the interleave to fix this, but then the last
// 4 bytes of the input data are lost due to the decoder's interleave
// being asymmetric.
//
// I'm stumped.
//
QVector<uint8_t> ReedSolomon::c2_encode(QVector<uint8_t> data) {
    // Convert the QVector to a std::vector for the ezpwd library
    std::vector<uint8_t> tmp_data(data.begin(), data.end());

    // Encode the data
    c2rs.encode(tmp_data);

    // Extract parity symbols
    std::vector<uint8_t> parity(tmp_data.begin() + 24, tmp_data.end());

    // Create the output QVector
    QVector<uint8_t> output_data = data.mid(0, 12) + QVector<uint8_t>(parity.begin(), parity.end()) + data.mid(12, 12);

    return output_data;
}

// Perform a C2 Reed-Solomon decoding operation on the input data
QVector<uint8_t> ReedSolomon::c2_decode(QVector<uint8_t> encoded_data) {
    // Convert the QVector to a std::vector for the ezpwd library
    std::vector<uint8_t> tmp_data(encoded_data.begin(), encoded_data.end());

    std::vector<int> position;
    std::vector<int> erasures;
    int fixed = -1;

    // Decode the data
    fixed = c2rs.decode(tmp_data, erasures, &position);

    if (fixed == 0) {
        qDebug() << "ReedSolomon::c2_decode - No errors found";
    } else {
        if (fixed > 0 && fixed <= 3) {
            qDebug() << "ReedSolomon::c2_decode - Fixed" << fixed << "errors";
        } else {
            if (fixed > 3) {
                qDebug() << "ReedSolomon::c2_decode - Too many errors to correct (" << fixed << ") C2 is lost";
                qFatal("ReedSolomon::c2_decode(): Too many errors to correct");
                tmp_data.clear();
            } else {
                qDebug() << "ReedSolomon::c2_decode - Unrecoverable errors found (" << fixed << ") C2 is lost";
                qFatal("ReedSolomon::c2_decode(): Too many errors to correct");
                tmp_data.clear();
            }
        }
    }

    // Convert the std::vector back to a QVector
    encoded_data = QVector<uint8_t>(tmp_data.begin(), tmp_data.end());

    return encoded_data;
}